name: Workflow using YAML from Test2

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  security-events: write
  attestations: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  statuses: write
  id-token: write

jobs:
  call-codeql-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/codeql_new.yml@main
    secrets: inherit

  call-shiftleft-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/shiftleft-analysis.yml@main
    secrets: inherit

  call-Policy-As-Code:
    uses: MyOrgHacker/Test2/.github/workflows/Pac.yml@main
    secrets: inherit

  call-docker-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/docker-image.yml@main
    secrets: inherit



